### ISSUE TITLE
 Fuzzy dates support

### ISSUE THREAD

**Issue by daonb** [daonb/tumuli#29]
User should be able to type-in or quick search for a fuzzy date.
Fuzzy date means that we accept various levels of time granularity to represent the time point of an event/story_item occurrence.
Examples:
a single/specific day (i.e., 11 Nov, 1985, 7/8/2008 - any date format)
a month in a year (i.e., March, 1945)
a year (i.e, 1973)
a period in a year (i.e., Winter 1938, something like the beginning of 1970)
range of years (i.e., 1973-1975; the 60th)
or some combination that can represent a day/ month/s /period in an estimated range of years (i.e., March 1974-1976)

For our use case, most frequent use is expected to be a year (then range of years followed by month/period in a year and only then a specific date).

I would consider that the default should be prompting the user with a year (YYYY? i.e., 1948), followed by (Month? i.e., Feb).

**Comment by HILITMA** [comment]
User should be able to type-in or quick search for a fuzzy date. examples: 'Winter, 1923', '1940', 'the 60th', '11 Nov, 1978', 'March 1945'.

**Comment by daonb** [comment]
We will use years for now
